// <auto-generated>
// UIFrame 生成，请勿手改。在 Inspector 绑定后点「写入脚本」。
// </auto-generated>
using UnityEngine;

namespace Game.Hotfix
{
    public partial class GomokuMainPanel
    {
        [SerializeField] private UnityEngine.UI.Image gomokuBg;
        [SerializeField] private UnityEngine.UI.Image checkerboard;
    }
}
