// <auto-generated>
// UIFrame 生成，请勿手改。在 Inspector 绑定后点「写入脚本」。
// </auto-generated>
using UnityEngine;

namespace Game.Hotfix
{
    public partial class WoodenFishMainPanel
    {
        [SerializeField] private UnityEngine.UI.Image fishImg;
        [SerializeField] private UnityEngine.UI.Image crabstick;
        [SerializeField] private TMPro.TextMeshProUGUI num;
        [SerializeField] private TMPro.TextMeshProUGUI clickNum;
    }
}
